#cloud-config
package_upgrade: true
packages:
  - curl
  - git
  - install
  - ca-certificates
  - gnupg
  - lsb-release
runcmd:
  # Installing kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  - chmod +x kubectl
  - mkdir -p ~/.local/bin/kubectl
  - mv ./kubectl ~/.local/bin/kubectl

  # Installing azure cli
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  # Installing docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io