apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Secrets are BASE64 encoded
  ConnectionStrings.CatalogDB: U2VydmVyPXNxbGRhdGE7RGF0YWJhc2U9TWljcm9zb2Z0LmVTaG9wT25EYXByLlNlcnZpY2VzLkNhdGFsb2dEYjtVc2VyIElkPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWUK
  ConnectionStrings.IdentityDB: U2VydmVyPXNxbGRhdGE7RGF0YWJhc2U9TWljcm9zb2Z0LmVTaG9wT25EYXByLlNlcnZpY2UuSWRlbnRpdHlEYjtVc2VyIElkPXNhO1Bhc3N3b3JkPVBhc3NAd29yZDtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWUK
  ConnectionStrings.OrderingDB: U2VydmVyPXNxbGRhdGE7RGF0YWJhc2U9TWljcm9zb2Z0LmVTaG9wT25EYXByLlNlcnZpY2VzLk9yZGVyaW5nRGI7VXNlciBJZD1zYTtQYXNzd29yZD1QYXNzQHdvcmQ7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVl
  RedisPassword: ZSRoMHAwbkRAcHI=
  Smtp.User: X3VzZXJuYW1l
  Smtp.Password: X3Bhc3N3b3Jk
