kind: Deployment
apiVersion: apps/v1
metadata:
  name: seq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: seq
  template:
    metadata:
      labels:
        app: eshop
        service: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        env:
          - name: ACCEPT_EULA
            value: "Y"

---

kind: Service
apiVersion: v1
metadata:
  name: seq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
      protocol: TCP
      name: http
  selector:
    service: seq
