name: Deploy All Microservices

on:
  workflow_dispatch:
    
jobs:
  BuildAndDeploy:
    uses: ./.github/workflows/dev-sec-ci.yml
    with:
      imageName: blazor-client
      projectPath: src/Web/BlazorClient.Host
      projectName: BlazorClient.Host.csproj
    secrets:
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      AZ_APPINSIGHTS_CONNECTION_STRING: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}  
      AZ_SUBSCRIPTION_TOKEN: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}     